Make error more user friendly if a user attempts to decommission a node
Instead of:

    UnsupportedFeatureException: Can't handle "AnalyzedDecommissionNodeStatement{nodeIdOrName=Literal{Wilde Leck, type=string}}

The users will now get:

    User "<name>" is not authorized to execute statement

(cherry picked from commit 8933baef8f11432847c6579a2666be2792d233af)

# Conflicts:
#	enterprise/users/src/main/java/io/crate/auth/user/StatementPrivilegeValidator.java